--- # Build and deploy packages
name: 'Publish to nuget using multi-push (wit symbols)'
description: 'Publishes Nuget packages with multi-push (wit symbols)'
inputs:
  NUGET_FEED:
    description: 'Nuget feed to push packages to'
    required: false
  NUGET_SYMBOL_FEED:
    description: 'Nuget feed to push packages symbols to'
    required: false
  NUGET_API_KEY:
    description: 'API key to authenticate when pushing packages'
    required: false

runs:
  using: "composite"
  steps:

    - name: "NuGet Push without Symbols"
      if: always()
      uses: ./.github/actions/dotnet-tool-run
      with:
        WORKING_DIRECTORY: "${{github.workspace}}"
        TOOL_NAME: "pushpackages"
        TOOL_ARGUMENTS: "--folder dist --api-key \"${{inputs.NUGET_API_KEY}}\" --source \"${{inputs.NUGET_FEED}}\" --symbol-source \"${{inputs.NUGET_SYMBOL_FEED}}\""
