--- # Run dotnet tool
name: 'Run dotnet tool'
description: 'Run dotnet tool'
inputs:
  WORKING_DIRECTORY:
    description: 'Working directory'
    required: true
    default: 'latest'
  TOOL_NAME:
    description: 'Tool to run'
    required: true
  TOOL_ARGUMENTS:
    description: 'Tool arguments'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: "Run dotnet tool (Latest)"
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: dotnet tool run --allow-roll-forward ${{inputs.TOOL_NAME}} ${{inputs.TOOL_ARGUMENTS}}
