--- # Run dotnet tool
name: 'Run dotnet tool'
description: 'Run dotnet tool'
inputs:
  WORKING_DIRECTORY:
    description: 'Working directory'
    required: true
    default: 'latest'
  TOOL_NAME:
    description: 'Tool to run'
    required: true
  TOOL_ARGUMENTS:
    description: 'Tool arguments'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:

    - name: "Run dotnet tool (Latest)"
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: dotnet tool run --allow-roll-forward \
              ${{inputs.TOOL_NAME}} \
              ${{inputs.TOOL_ARGUMENTS}}
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

