--- # Install dotnet tool
# Maintain in repo: funfair-server-template
name: 'Install dotnet tool'
description: 'Install dotnet tool'
inputs:
  tool-name:
    description: 'Tool to install'
    required: true
  tool-version:
    description: 'Tool version to install'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: "Install dotnet tool"
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        TOOL_NAME: ${{inputs.tool-name}}
        TOOL_VERSION: ${{inputs.tool-version}}
      run: |
        VERSION_ARGS=()
        [ "$TOOL_VERSION" != 'latest' ] && VERSION_ARGS=(--version "$TOOL_VERSION")
        r=5
        while ! dotnet tool install --local "$TOOL_NAME" "${VERSION_ARGS[@]}" --create-manifest-if-needed --ignore-failed-sources --verbosity diag; do
          ((--r)) || exit 1
          sleep 30
        done
