--- # Install dotnet tool
name: 'Install dotnet tool'
description: 'Install dotnet tool'
inputs:
  TOOL_NAME:
    description: 'Tool to install'
    required: true
  TOOL_VERSION:
    description: 'Tool version to install'
    required: false
    default: 'latest'
  NUGET_SOURCE:
    description: 'Nuget source'
    required: false
    default: 'https://api.nuget.org/v3/index.json'

runs:
  using: "composite"
  steps:

    - name: "Install dotnet tool (Latest)"
      if: inputs.TOOL_VERSION == 'latest'
      shell: bash
      run: |
        dotnet tool install \
            --global \
            --no-http-cache \
            --framework "$(dotnet --list-sdks | cut -f 1 -d " " | grep "^[0-9]*\.[0-9]*\.[0-9]*$" | sort | tail -1)" \
            --source "${{inputs.NUGET_SOURCE}}" \
            "${{inputs.TOOL_NAME}}"
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    - name: "Install dotnet tool (Specific Version)"
      if: inputs.TOOL_VERSION != 'latest'
      shell: bash
      run: |
          dotnet tool install \
              --global \
              --no-http-cache \
              --framework "$(dotnet --list-sdks | cut -f 1 -d " " | grep "^[0-9]*\.[0-9]*\.[0-9]*$" | sort | tail -1)" \
              --source "${{inputs.NUGET_SOURCE}}" \
              "${{inputs.TOOL_NAME}}" \
              --version ${{inputs.TOOL_VERSION}}
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    - name: "Restore"
      shell: bash
      run: dotnet tool restore

