---
extends: default
rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: enable
  indentation:
    spaces: 2
    indent-sequences: true
  line-length:
    max: 160
  truthy:
    allowed-values: ["true", "false", "on"]
