--- # Build Docker container and optionally deploy to ACR
# Maintain in repo: funfair-server-template
name: 'Build Docker container and optionally deploy to ACR'
description: 'Builds a docker image and optionally pushes it to AWS ECR'
inputs:
  deploy:
    description: 'Whether to deploy'
    required: true
  github-token:
    description: 'github token for accessing github'
    required: true
  build-version:
    description: 'Build version'
    required: true
  build-tag:
    description: 'Build tag'
    required: true
  app-owner:
    description: 'docker app owner'
    required: true
  app-name:
    description: 'docker app name'
    required: true
  docker-container-registry:
    description: 'AWS Elastic Container Registry'
    required: true
    default: '117769150821.dkr.ecr.eu-west-1.amazonaws.com'
  container-source:
    description: 'Location of app container source'
    required: true
  container-platform:
    description: 'Container platform'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Docker Trust Enable"
      shell: bash
      run: |
        echo "DOCKER_CONTENT_TRUST_ORIGINAL=${{env.DOCKER_CONTENT_TRUST}}" >> "$GITHUB_ENV"
        echo "DOCKER_CONTENT_TRUST=1" >> "$GITHUB_ENV"

    - name: "Build and export docker container"
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: ${{inputs.container-source}}
        load: true
        tags: ${{inputs.app-owner}}/${{inputs.app-name}}:test
#        cache-from: type=gha
#        cache-to: type=gha,mode=max

    ## Run docker image tests
    - name: "Run docker image tests"
      uses: ./.github/actions/docker-image-test
      with:
        app-owner: ${{inputs.app-owner}}
        app-name: ${{inputs.app-name}}
        github-token: ${{inputs.github-token}}

    - name: "Docker: Build with tags"
      if: inputs.deploy == 'true'
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: ${{inputs.container-source}}
        platforms: ${{inputs.container-platform}}
        push: ${{inputs.deploy}}
        tags: |
          ${{inputs.docker-container-registry}}/${{inputs.app-owner}}/${{inputs.app-name}}:${{inputs.build-tag}}
          ${{inputs.docker-container-registry}}/${{inputs.app-owner}}/${{inputs.app-name}}:${{inputs.build-version}}
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
        provenance: false

    - name: "Docker Trust Restore"
      shell: bash
      run: echo "DOCKER_CONTENT_TRUST=${{env.DOCKER_CONTENT_TRUST_ORIGINAL}}" >> "$GITHUB_ENV"
