--- # Build and deploy packages
# Maintain in repo: funfair-server-template
name: 'Publish to Sleet'
description: 'Publishes Nuget packages with sleet'
inputs:
  sleet-config:
    description: 'Sleet config file'
    required: false
  sleet-feed:
    description: 'Sleet feed to push packages to'
    required: false

runs:
  using: "composite"
  steps:

    - name: "Install Sleet package management tool"
      if: env.SLEET_TOOL_INSTALLED != 'true'
      uses: ./.github/actions/dotnet-tool
      with:
        tool-name: "sleet"
        tool-version: "latest"

    - name: "Mark Sleet package management tool installed"
      shell: bash
      run: echo "SLEET_TOOL_INSTALLED=true" >> "$GITHUB_ENV"

    - name: "Sleet: Generate Sleet Config"
      id: sleet-config
      uses: ./.github/actions/save-secret-as-file
      with:
        secret: ${{inputs.sleet-config}}

    - name: "Sleet: Publish Packages to Nuget (Using Sleet)"
      uses: ./.github/actions/dotnet-tool-run
      with:
        working-directory: "${{github.workspace}}"
        tool-name: "sleet"
        tool-arguments: "push \"${{github.workspace}}/dist\" --config \"${{steps.sleet-config.outputs.file}}\" --source \"${{inputs.sleet-feed}}\""

    - name: "Sleet: Clean Up Sleet Config"
      if: always()
      shell: bash
      run: |
        rm -f "${FILE}"
      env:
        FILE: "${{steps.sleet-config.outputs.file}}"
