--- # Build and deploy packages
name: 'Publish to Sleet'
description: 'Publishes Nuget packages with sleet'
inputs:
  SLEET_CONFIG:
    description: 'Sleet config file'
    required: false
  SLEET_FEED:
    description: 'Sleet feed to push packages to'
    required: false

runs:
  using: "composite"
  steps:

    - name: "Sleet: Generate Sleet Config"
      uses: joutvhu/write-file@v1
      with:
        path: sleet.json
        contents: ${{ inputs.SLEET_CONFIG }}
        write_mode: overwrite

    - name: "Sleet: Publish Packages to Nuget (Using Sleet)"
      shell: bash
      run: dotnet sleet push "${{github.workspace}}/dist" --config sleet.json --source ${{inputs.SLEET_FEED}}
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
