--- # Build SQL
name: 'Build SQL'
description: 'Builds SQL Package'
inputs:
  # General
  BUILD_VERSION:
    description: 'Build version'
    required: true

  DB_FOLDER:
    description: 'Folder where SQL Files live'
    required: true

runs:
  using: "composite"
  steps:

  - name: "SQL: Install TSQLLint"
    uses: ./.github/actions/dotnet-tool
    with:
      TOOL_NAME: TSQLLint
      TOOL_VERSION: latest

  - name: "SQL: Lint SQL Files (TSQLLint)"
    uses: ./.github/actions/dotnet-tool-run
    with:
      TOOL_NAME: tsqllint
      TOOL_ARGUMENTS: "${{inputs.DB_FOLDER}}"
      WORKING_DIRECTORY: ${{github.workspace}}

  - name: "SQL: Lint SQL Files (SQLFluff)"
    uses: super-linter/super-linter@v8.5.0
    env:
      GITHUB_TOKEN: ${{secrets.SOURCE_PUSH_TOKEN}}
      SAVE_SUPER_LINTER_SUMMARY: false
      MULTI_STATUS: true
      VALIDATE_SQLFLUFF: true
      SQLFLUFF_CONFIG_FILE: .sqlfluff
