--- # Build SQL
name: 'Build SQL'
description: 'Builds SQL Package'
inputs:
  # General
  BUILD_VERSION:
    description: 'Build version'
    required: true

  DB_FOLDER:
    description: 'Folder where SQL Files live'
    required: true

  # GITHUB
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true

runs:
  using: "composite"
  steps:

  - name: "SQL: Install TSQLLint"
    uses: ./.github/actions/dotnet-tool
    with:
      TOOL_NAME: "TSQLLint"
      TOOL_VERSION: "latest"

  - name: "SQL: Lint SQL Files (TSQLLint)"
    uses: ./.github/actions/dotnet-tool-run
    with:
      TOOL_NAME: "tsqllint"
      TOOL_ARGUMENTS: "${{inputs.DB_FOLDER}}"
      WORKING_DIRECTORY: ${{github.workspace}}

  - name: "SQL: Lint SQL Files (SQLFluff)"
    uses: super-linter/super-linter@v8.6.0
    env:
      GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
      ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
      ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: false
      SAVE_SUPER_LINTER_SUMMARY: false
      MULTI_STATUS: false
      VALIDATE_SQLFLUFF: true
      SQLFLUFF_CONFIG_FILE: .sqlfluff
