--- # Dotnet Build Check
name: 'Dotnet Build Check'
description: 'Dotnet Build Check'
inputs:
  # GENERAL
  RELEASE:
    description: 'Is this a release build'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Dotnet: Run build check (Pre-Release)"
      if: inputs.RELEASE == 'false'
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
        echo "Looking for solution"
        SOLUTION="$(find . -type f -iname "*.sln" | head -1)"
        [ -z "$SOLUTION" ] && SOLUTION="$(find . -type f -iname "*.slnx" | head -1)"
        echo "Found: $SOLUTION"
        dotnet tool run buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild false
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    - name: "Dotnet: Run build check (Release)"
      if: inputs.RELEASE == 'true'
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
        echo "Looking for solution"
        SOLUTION="$(find . -type f -iname "*.sln" | head -1)"
        [ -z "$SOLUTION" ] && SOLUTION="$(find . -type f -iname "*.slnx" | head -1)"
        echo "Found: $SOLUTION"
        dotnet tool run buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild false
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
