--- # Dotnet Build Check
name: 'Dotnet Build Check'
description: 'Dotnet Build Check'
inputs:
  # GENERAL
  RELEASE:
    description: 'Is this a release build'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Dotnet: Find Solution"
      id: find_solution
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
        echo "Looking for solution"
        SOLUTION="$(find . -type f -iname "*.sln" | head -1)"
        [ -z "$SOLUTION" ] && SOLUTION="$(find . -type f -iname "*.slnx" | head -1)"
        echo "Found: $SOLUTION"
        echo "SOLUTION=$SOLUTION" >> "$GITHUB_OUTPUT"

    - name: "Dotnet: Run build check (Pre-Release)"
      if: inputs.RELEASE == 'false'
      uses: ./.github/actions/dotnet-tool-run
      with:
        WORKING_DIRECTORY: "${{github.workspace}}/src"
        TOOL_NAME: "buildcheck"
        TOOL_ARGUMENTS: "-Solution \"${{steps.find_solution.outputs.SOLUTION}}\" -WarningAsErrors true -PreReleaseBuild false"

    - name: "Dotnet: Run build check (Release)"
      if: inputs.RELEASE == 'true'
      uses: ./.github/actions/dotnet-tool-run
      with:
        WORKING_DIRECTORY: "${{github.workspace}}/src"
        TOOL_NAME: "buildcheck"
        TOOL_ARGUMENTS: "-Solution \"$SOLUTION\" -WarningAsErrors true -PreReleaseBuild false"
