--- # Setup Docker
# Maintain in repo: funfair-server-template
name: 'Setup Docker'
description: 'Setup docker'
inputs:
  aws-access-key-id:
    description: 'AWS Access key'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  docker-container-registry:
    description: 'AWS Elastic Container Registry'
    required: true
  docker-username:
    description: 'Docker username'
    required: true
  docker-access-token:
    description: 'Docker access token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

    - name: "Configure AWS Credentials"
      if: inputs.aws-access-key-id != ''
      uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
      with:
        aws-access-key-id: ${{inputs.aws-access-key-id}}
        aws-secret-access-key: ${{inputs.aws-secret-access-key}}
        aws-region: ${{inputs.aws-region}}

    - name: "Docker: Login to Docker Hub"
      if: inputs.docker-access-token != ''
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        username: ${{inputs.docker-username}}
        password: ${{inputs.docker-access-token}}
        ecr: false

    - name: "Docker: Login to AWS ECR"
      if: inputs.aws-access-key-id != ''
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ${{inputs.docker-container-registry}}
        ecr: true

    - name: "Docker: Login to GitHub Container Registry"
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{github.token}}
