--- # Setup Docker
name: 'Setup Docker'
description: 'Setup docker'
inputs:
  AWS-ACCESS-KEY-ID:
    description: 'AWS Access key'
    required: true
  AWS-SECRET-ACCESS-KEY:
    description: 'AWS Secret key'
    required: true
  AWS-REGION:
    description: 'AWS region'
    required: true
  AWS-CONTAINER-REGISTRY:
    description: 'AWS Elastic Container Registry'
    required: true
  DOCKER_USERNAME:
    description: 'Docker username'
    required: true
  DOCKER_ACCESS_TOKEN:
    description: 'Docker access token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3.0.0

    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{inputs.AWS-ACCESS-KEY-ID}}
        aws-secret-access-key: ${{inputs.AWS-SECRET-ACCESS-KEY}}
        aws-region: ${{inputs.AWS-REGION}}

    - name: "Docker: Login to Docker Hub"
      uses: docker/login-action@v3.0.0
      with:
        username: ${{inputs.DOCKER_USERNAME}}
        password: ${{inputs.DOCKER_ACCESS_TOKEN}}
        ecr: false

    - name: "Docker: Login to AWS ECR"
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{inputs.AWS-CONTAINER-REGISTRY}}
        ecr: true
