--- # Setup Docker
name: 'Setup Docker'
description: 'Setup docker'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS Access key'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Secret key'
    required: true
  AWS_REGION:
    description: 'AWS region'
    required: true
  AWS_CONTAINER_REGISTRY:
    description: 'AWS Elastic Container Registry'
    required: true
  DOCKER_USERNAME:
    description: 'Docker username'
    required: true
  DOCKER_ACCESS_TOKEN:
    description: 'Docker access token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3.0.0

    - name: "Configure AWS Credentials"
      if: inputs.AWS_ACCESS_KEY_ID != ''
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{inputs.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{inputs.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{inputs.AWS_REGION}}

    - name: "Docker: Login to Docker Hub"
      if: inputs.DOCKER_ACCESS_TOKEN != ''
      uses: docker/login-action@v3.0.0
      with:
        username: ${{inputs.DOCKER_USERNAME}}
        password: ${{inputs.DOCKER_ACCESS_TOKEN}}
        ecr: false

    - name: "Docker: Login to AWS ECR"
      if: inputs.AWS_ACCESS_KEY_ID != ''
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{inputs.AWS_CONTAINER_REGISTRY}}
        ecr: true
