--- # Run docker image tests
# Maintain in repo: funfair-server-template
name: 'Run docker image tests'
description: 'Docker image tests'
inputs:
  app-owner:
    description: 'docker app owner'
    required: true
  app-name:
    description: 'docker app name'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run Trivy vulnerability scanner"
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        image-ref: "${{inputs.app-owner}}/${{inputs.app-name}}:test"
        format: "table"
        exit-code: "1"
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "HIGH,CRITICAL"
        cache-dir: "${{github.workspace}}/.trivy-cache"
