--- # Build and deploy packages
name: 'Build and deploy'
description: 'Builds and deploys the source'
inputs:
  SQL_SERVER:
    description: 'SQL Server to connect to'
    required: true
  SQL_DB:
    description: 'Database to deploy to'
    required: true
  SQL_USER:
    description: 'User to connect to the database as'
    required: true
  SQL_PASSWORD:
    description: 'Password for SQL_USER'
    required: true
  DB_FOLDER:
    description: 'Folder where SQL Files live'
    required: true

runs:
  using: "composite"
  steps:

    - name: "Dotnet: Find Dacpac"
      id: find_dacpac
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
        echo "Looking for dacpac"
        DACPAC="$(find "${{github.workspace}}/src" -type f -iname "*.dacpac" | head -1)"
        echo "Found: $DACPAC"
        [ -z "$DACPAC" ] && echo "Error: DACPAC not found!" && exit 1
        echo "DACPAC=$DACPAC" >> "$GITHUB_OUTPUT"

    - name: "Install SQLPackage tool"
      uses: ./.github/actions/dotnet-tool
      with:
        TOOL_NAME: "microsoft.sqlpackage"
        TOOL_VERSION: "latest"

# yamllint disable rule:line-length
#     Would be nice to use this, but it requires a dotnet tool to be installed anyway so may as well do it all ourselves
#    - name: "DB: Deploy..."
#      uses: azure/sql-action@v2.3
#      with:
#        connection-string: "Server=${{inputs.SQL_SERVER}};Database=${{inputs.SQL_DB}};User Id=${{inputs.SQL_USER}};Password=${{inputs.SQL_PASSWORD}};Connection Timeout=720;TrustServerCertificate=true;Application Name=Deploy Database"
#        path: "${{steps.find_solution.outputs.DACPAC}}"
#        action: 'publish'
#        arguments: '/p:DoNotDropObjectTypes=Aggregates;ApplicationRoles;Assemblies;AssemblyFiles;AsymmetricKeys;BrokerPriorities;Certificates;ColumnEncryptionKeys;ColumnMasterKeys;Contracts;DatabaseOptions;DatabaseRoles;Filegroups;Files;FileTables;RoleMembership;Rules;Users;Credentials;CryptographicProviders;DatabaseAuditSpecifications;DatabaseEncryptionKeys;DatabaseScopedCredentials;Endpoints;LinkedServerLogins;LinkedServers;Logins;MasterKeys;Routes;ServerAuditSpecifications;ServerRoleMembership;ServerRoles;ServerTriggers'
# yamllint enable rule:line-length

    - name: "Pass"
      working-directory: ${{github.workspace}}/src
      shell: bash
      env:
        PASS: ${{inputs.SQL_PASSWORD}}
      run: echo "$PASS" | base64

    - name: "Dotnet: Test SQL Password"
      if: inputs.SQL_PASSWORD == ''
      working-directory: ${{github.workspace}}/src
      shell: bash
      run:
        echo "Missing SQL Password!"
        exit 1

# yamllint disable rule:line-length
    - name: "Dotnet: Deploy/Live Server"
      working-directory: ${{github.workspace}}/src
      shell: bash
      # yamllint disable rule:line-length
      run: |
        dotnet tool run --allow-roll-forward sqlpackage \
            /Action:publish \
            /sf:"$DACPAC_FILE" \
            /tsn:"$SQL_SERVER" \
            /tdn:"$SQL_DB" \
            /tu:"$SQL_USER" \
            /tp:"$SQL_PASSWORD" \
            /tec:false \
            /d:true \
            /TargetTimeout:${{env.TIMEOUT}} \
            /p:CommandTimeout=${{env.TIMEOUT}} \
            /p:BackupDatabaseBeforeChanges=False \
            /p:BlockOnPossibleDataLoss=True \
            /p:DropObjectsNotInSource=True \
            "/p:DoNotDropObjectTypes=Aggregates;ApplicationRoles;Assemblies;AssemblyFiles;AsymmetricKeys;BrokerPriorities;Certificates;ColumnEncryptionKeys;ColumnMasterKeys;Contracts;DatabaseOptions;DatabaseRoles;Filegroups;Files;FileTables;RoleMembership;Rules;Users;Credentials;CryptographicProviders;DatabaseAuditSpecifications;DatabaseEncryptionKeys;DatabaseScopedCredentials;Endpoints;LinkedServerLogins;LinkedServers;Logins;MasterKeys;Routes;ServerAuditSpecifications;ServerRoleMembership;ServerRoles;ServerTriggers" \
            /p:IncludeCompositeObjects=True
      # yamllint enable rule:line-length
      env:
        DACPAC_FILE: "${{steps.find_dacpac.outputs.DACPAC}}"
        SQL_SERVER: "${{inputs.SQL_SERVER}}"
        SQL_DB: "${{inputs.SQL_DB}}"
        SQL_USER: "${{inputs.SQL_USER}}"
        SQL_PASSWORD: "${{inputs.SQL_PASSWORD}}"
        TIMEOUT: 720
# yamllint enable rule:line-length

# yamllint disable rule:line-length
#    - name: "Dotnet: Deploy/Live Server"
#      uses: ./.github/actions/dotnet-tool-run
#      with:
#        WORKING_DIRECTORY: "${{github.workspace}}/src"
#        TOOL_NAME: "sqlpackage"
#        TOOL_ARGUMENTS: "/Action:publish \
#            /sf:\"${{steps.find_solution.outputs.DACPAC}}\" \
#            /tsn:\"${{inputs.SQL_SERVER}}\" \
#            /tdn:\"${{inputs.SQL_DB}}\" \
#            /tu:\"${{inputs.SQL_USER}}\" \
#            /tp:\"${{inputs.SQL_PASSWORD}}\" \
#            /tec:false \
#            /d:true \
#            /p:CommandTimeout=720 \
#            /p:BackupDatabaseBeforeChanges=False \
#            /p:BlockOnPossibleDataLoss=True \
#            /p:DropObjectsNotInSource=True \
#            \"/p:DoNotDropObjectTypes=Aggregates;ApplicationRoles;Assemblies;AssemblyFiles;AsymmetricKeys;BrokerPriorities;Certificates;ColumnEncryptionKeys;ColumnMasterKeys;Contracts;DatabaseOptions;DatabaseRoles;Filegroups;Files;FileTables;RoleMembership;Rules;Users;Credentials;CryptographicProviders;DatabaseAuditSpecifications;DatabaseEncryptionKeys;DatabaseScopedCredentials;Endpoints;LinkedServerLogins;LinkedServers;Logins;MasterKeys;Routes;ServerAuditSpecifications;ServerRoleMembership;ServerRoles;ServerTriggers\" \
#            /p:IncludeCompositeObjects=True"
# yamllint enable rule:line-length
#
#
