--- # Build and deploy packages
# Maintain in repo: funfair-server-template
name: 'Install dotnet and build tools'
description: 'Install dotnet and build tools'
inputs:
  # GENERAL
  github-token:
    description: 'Github Token'
    required: true

  # NUGET
  nuget-public-restore-feed-cache:
    description: 'Local cache of public nuget feed'
    required: false
  nuget-public-restore-feed:
    description: 'public nuget feed'
    required: false
  nuget-additional-restore-feed-release-cache:
    description: 'Any additional nuget feed to download packages from'
    required: false
  nuget-additional-restore-feed-prerelease-cache:
    description: 'Any additional nuget feed to download packages from'
    required: false
  nuget-additional-restore-feed-release:
    description: 'Any additional nuget feed to download packages from'
    required: false
  nuget-additional-restore-feed-prerelease:
    description: 'Any additional nuget feed to download packages from'
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install dotnet"
      uses: ./.github/actions/dotnet-install
      with:
        github-token: ${{inputs.github-token}}
        nuget-public-restore-feed-cache: ${{inputs.nuget-public-restore-feed-cache}}
        nuget-public-restore-feed: ${{inputs.nuget-public-restore-feed}}
        nuget-additional-restore-feed-release-cache: ${{inputs.nuget-additional-restore-feed-release-cache}}
        nuget-additional-restore-feed-prerelease-cache: ${{inputs.nuget-additional-restore-feed-prerelease-cache}}
        nuget-additional-restore-feed-release: ${{inputs.nuget-additional-restore-feed-release}}
        nuget-additional-restore-feed-prerelease: ${{inputs.nuget-additional-restore-feed-prerelease}}

    - name: "Install Build Version Tool"
      uses: ./.github/actions/dotnet-tool
      with:
        tool-name: "FunFair.BuildVersion"
        tool-version: "latest"
