--- # Build and deploy packages
name: 'Install dotnet and build tools'
description: 'Install dotnet and build tools'
inputs:
  # GENERAL
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true

  # NUGET
  NUGET_PUBLIC_RESTORE_FEED_CACHE:
    description: 'Local cache of public nuget feed'
    required: false
  NUGET_PUBLIC_RESTORE_FEED:
    description: 'public nuget feed'
    required: false
  NUGET_ADDITIONAL_RESTORE_FEED_RELEASE_CACHE:
    description: 'Any additional nuget feed to download packages from'
    required: false
  NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE_CACHE:
    description: 'Any additional nuget feed to download packages from'
    required: false
  NUGET_ADDITIONAL_RESTORE_FEED_RELEASE:
    description: 'Any additional nuget feed to download packages from'
    required: false
  NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE:
    description: 'Any additional nuget feed to download packages from'
    required: false

runs:
  using: "composite"
  steps:

  - name: "Determine dotnet version"
    uses: credfeto/action-dotnet-version-detect@v1.3.0
    with:
      file: src/global.json
      fallback: 7.0.*

  - name: "Explicitly kill any existing dotnet"
    run: rm -fr "${{github.workspace}}/.dotnet"
    shell: bash

  - name: "Install dotnet"
    uses: actions/setup-dotnet@v4.0.1
    env:
      GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
      DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
      DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
      DOTNET_MULTILEVEL_LOOKUP: "false"
      DOTNET_NOLOGO: "true"
      DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
      DOTNET_JitCollect64BitCounts: "1"
      DOTNET_ReadyToRun: "0"
      DOTNET_TC_QuickJitForLoops: "1"
      DOTNET_TC_CallCountingDelayMs: "0"
      DOTNET_TieredPGO: "1"
      MSBUILDTERMINALLOGGER: "auto"
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    with:
      dotnet-version: |
          6.0.*
          7.0.*
          8.0.*
          ${{env.DOTNET_VERSION}}

  - name: "Configure nuget feeds"
    uses: ./.github/actions/nuget
    with:
      NUGET_PUBLIC_RESTORE_FEED_CACHE: ${{inputs.NUGET_PUBLIC_RESTORE_FEED_CACHE}}
      NUGET_PUBLIC_RESTORE_FEED: ${{inputs.NUGET_PUBLIC_RESTORE_FEED}}
      NUGET_ADDITIONAL_RESTORE_FEED_RELEASE_CACHE: ${{inputs.NUGET_ADDITIONAL_RESTORE_FEED_RELEASE_CACHE}}
      NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE_CACHE: ${{inputs.NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE_CACHE}}
      NUGET_ADDITIONAL_RESTORE_FEED_RELEASE: ${{inputs.NUGET_ADDITIONAL_RESTORE_FEED_RELEASE}}
      NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE: ${{inputs.NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE}}

  - name: "Enable dotnet tools"
    shell: bash
    working-directory: ${{ github.workspace }}
    run: |
      [ ! -f .config/dotnet-tools.json ] && dotnet new tool-manifest
      dotnet tool restore || true
    env:
      DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
      DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
      DOTNET_MULTILEVEL_LOOKUP: "false"
      DOTNET_NOLOGO: "true"
      DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
      DOTNET_JitCollect64BitCounts: "1"
      DOTNET_ReadyToRun: "0"
      DOTNET_TC_QuickJitForLoops: "1"
      DOTNET_TC_CallCountingDelayMs: "0"
      DOTNET_TieredPGO: "1"
      MSBUILDTERMINALLOGGER: "auto"
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

  - name: "Install Sleet package management tool"
    uses: ./.github/actions/dotnet-tool
    with:
      TOOL_NAME: sleet
      TOOL_VERSION: latest

  - name: "Install Build Version Tool"
    uses: ./.github/actions/dotnet-tool
    with:
      TOOL_NAME: FunFair.BuildVersion
      TOOL_VERSION: latest

  - name: "Install Changelog Tool"
    uses: ./.github/actions/dotnet-tool
    with:
      TOOL_NAME: Credfeto.Changelog.Cmd
      TOOL_VERSION: latest
