--- # Sync labels on a pull request based on the labeler configuration
name: "Sync PR Labels"
description: "Syncs labels on a pull request based on the labeler configuration"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  pr-number:
    description: "Pull request number to label"
    required: true

runs:
  using: composite
  steps:
    - name: "Sync Labels"
      uses: actions/labeler@v6.0.1
      with:
        repo-token: ${{inputs.github-token}}
        configuration-path: .github/labeler.yml
        sync-labels: true
        pr-number: ${{inputs.pr-number}}
