--- # Define build version properties
name: 'Define Build Version'
description: 'Defines the build version properties'
inputs:
  # GENERAL
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Get Unique Build Number"
      uses: onyxmueller/build-tag-number@v1.0.3
      id: build-number
      with:
        token: ${{inputs.GITHUB_TOKEN}}
        prefix: github

    - name: "Set Define Build Version"
      shell: bash
      run: dotnet buildversion --BuildNumber "${{steps.build-number.outputs.build_number}}"
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    - name: "Log build version"
      shell: bash
      run: |
        echo "****************************************************************"
        echo "* Current Build: ${{env.BUILD_VERSION}}"
        echo "****************************************************************"
