--- # Define build version properties
name: 'Define Build Version'
description: 'Defines the build version properties'
inputs:
  # GENERAL
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Define Build Version"
      uses: ./.github/actions/dotnet-tool-run
      with:
        WORKING_DIRECTORY: "${{github.workspace}}"
        TOOL_NAME: "buildversion"
        TOOL_ARGUMENTS: "--GithubToken \"${{inputs.GITHUB_TOKEN}}\" --TagPrefix \"github\""

    - name: "Log build version"
      shell: bash
      run: |
        echo "****************************************************************"
        echo "* Current Build: ${{env.BUILD_VERSION}}"
        echo "****************************************************************"
