using System;
using Credfeto.Enumeration.Source.Generation.Builders;
using FunFair.Test.Common;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace Credfeto.Enumeration.Source.Generation.Tests.Builders;

public sealed class CodeBuilderTests : TestBase
{
    [Fact]
    public void AppendLineAddsTextWithNewLine()
    {
        CodeBuilder builder = new();
        builder.AppendLine("hello");

        string text = builder.Text.ToString();
        Assert.Contains("hello", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendLineWithWhitespaceOnlyAddsBlankLine()
    {
        CodeBuilder builder = new();
        builder.AppendLine("   ");

        string text = builder.Text.ToString();
        Assert.Equal(Environment.NewLine, text);
    }

    [Fact]
    public void AppendBlankLineAddsEmptyLine()
    {
        CodeBuilder builder = new();
        builder.AppendBlankLine();

        string text = builder.Text.ToString();
        Assert.Equal(Environment.NewLine, text);
    }

    [Fact]
    public void AppendFileHeaderContainsAutoGeneratedComment()
    {
        CodeBuilder builder = new();
        builder.AppendFileHeader();

        string text = builder.Text.ToString();
        Assert.Contains("<auto-generated>", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendGeneratedCodeAttributeContainsGeneratedCode()
    {
        CodeBuilder builder = new();
        builder.AppendGeneratedCodeAttribute();

        string text = builder.Text.ToString();
        Assert.Contains("GeneratedCode", text, StringComparison.Ordinal);
    }

    [Fact]
    public void StartBlockAppendsTextAndBraces()
    {
        CodeBuilder builder = new();
        using (builder.StartBlock("public static class Foo"))
        {
            builder.AppendLine("// body");
        }

        string text = builder.Text.ToString();
        Assert.Contains("public static class Foo", text, StringComparison.Ordinal);
        Assert.Contains("{", text, StringComparison.Ordinal);
        Assert.Contains("}", text, StringComparison.Ordinal);
    }

    [Fact]
    public void StartBlockWithCustomStartAndEndAppendsCorrectly()
    {
        CodeBuilder builder = new();
        using (builder.StartBlock("return value switch", start: "{", end: "};"))
        {
            builder.AppendLine("A => \"A\",");
        }

        string text = builder.Text.ToString();
        Assert.Contains("return value switch", text, StringComparison.Ordinal);
        Assert.Contains("{", text, StringComparison.Ordinal);
        Assert.Contains("};", text, StringComparison.Ordinal);
    }

    [Fact]
    public void NestedStartBlockIndentsContent()
    {
        CodeBuilder builder = new();
        using (builder.StartBlock("public class Outer"))
        {
            using (builder.StartBlock("public class Inner"))
            {
                builder.AppendLine("// content");
            }
        }

        string text = builder.Text.ToString();
        // Content inside nested blocks should be indented
        Assert.Contains("        // content", text, StringComparison.Ordinal);
    }

    [Fact]
    public void TextPropertyReturnsSourceText()
    {
        CodeBuilder builder = new();
        builder.AppendLine("test");

        SourceText sourceText = builder.Text;
        Assert.NotNull(sourceText);
        Assert.Contains("test", sourceText.ToString(), StringComparison.Ordinal);
    }

    [Fact]
    public void AppendLineReturnsBuilderForChaining()
    {
        CodeBuilder builder = new();
        CodeBuilder result = builder.AppendLine("line1").AppendLine("line2");

        Assert.Same(expected: builder, actual: result);
    }

    [Fact]
    public void AppendBlankLineReturnsBuilderForChaining()
    {
        CodeBuilder builder = new();
        CodeBuilder result = builder.AppendBlankLine().AppendBlankLine();

        Assert.Same(expected: builder, actual: result);
    }

    [Fact]
    public void IndentIsDecrementedAfterDispose()
    {
        CodeBuilder builder = new();
        builder.AppendLine("before block");

        IDisposable block = builder.StartBlock("class X");
        builder.AppendLine("inside");
        block.Dispose();

        builder.AppendLine("after block");

        string text = builder.Text.ToString();
        // After disposal, indentation should be back to zero for "after block"
        Assert.Contains("after block", text, StringComparison.Ordinal);
        // "inside" should be indented 4 spaces (one indent level inside the block)
        Assert.Contains("    inside", text, StringComparison.Ordinal);
    }
}
