--- # Override Code Dotnet Analysis settings
name: 'Override Code Dotnet Analysis settings'
description: 'Override Code Dotnet Analysis settings'
inputs:
  # GENERAL
  RELEASE:
    description: 'Is this a release build'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Dotnet: Override code analysis settings (Pre-Release)"
      if: inputs.RELEASE == 'false'
      uses: ./.github/actions/dotnet-tool-run
      with:
        WORKING_DIRECTORY: "${{github.workspace}}/src"
        TOOL_NAME: "code-analysis"
        TOOL_ARGUMENTS: "globalconfig --ruleset \"${{github.workspace}}/.globalconfig\" --changes \"${{github.workspace}}/src/pre-release.rule-settings.json\""

    - name: "Dotnet: Override code analysis settings (Release)"
      if: inputs.RELEASE == 'true'
      uses: ./.github/actions/dotnet-tool-run
      with:
        WORKING_DIRECTORY: "${{github.workspace}}/src"
        TOOL_NAME: "code-analysis"
        TOOL_ARGUMENTS: "globalconfig --ruleset \"${{github.workspace}}/.globalconfig\" --changes \"${{github.workspace}}/src/release.rule-settings.json\""
