--- # Override Code Dotnet Analysis settings
# Maintain in repo: funfair-server-template
name: 'Override Code Dotnet Analysis settings'
description: 'Override Code Dotnet Analysis settings'
inputs:
  # GENERAL
  release:
    description: 'Is this a release build'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install Dotnet code analysis overrides tool"
      uses: ./.github/actions/dotnet-tool
      with:
        tool-name: "Credfeto.DotNet.Code.Analysis.Overrides.Cmd"
        tool-version: "latest"

    - name: "Dotnet: Override code analysis settings (Pre-Release)"
      if: inputs.release == 'false'
      uses: ./.github/actions/dotnet-tool-run
      with:
        working-directory: "${{github.workspace}}/src"
        tool-name: "code-analysis"
        tool-arguments: "globalconfig --ruleset \"${{github.workspace}}/.globalconfig\" --changes \"${{github.workspace}}/src/pre-release.rule-settings.json\""

    - name: "Dotnet: Override code analysis settings (Release)"
      if: inputs.release == 'true'
      uses: ./.github/actions/dotnet-tool-run
      with:
        working-directory: "${{github.workspace}}/src"
        tool-name: "code-analysis"
        tool-arguments: "globalconfig --ruleset \"${{github.workspace}}/.globalconfig\" --changes \"${{github.workspace}}/src/release.rule-settings.json\""
