<Project>
    <!-- In .targets, not .props: $(TargetFramework) is unset for single-targeting projects until after the project body -->

    <!-- Sarif -->
    <PropertyGroup Condition="$(EnableSarif)=='True' And !$(MSBuildProjectName.EndsWith('.Tests'))">
        <ErrorLog>$(SolutionDir)\..\results\$(MSBuildProjectName).$(TargetFramework).sarif,version=2.1</ErrorLog>
    </PropertyGroup>

    <!-- Code analysis analyzer - report timings -->
    <PropertyGroup Condition="$(EnableSarif)=='True' And !$(MSBuildProjectName.EndsWith('.Tests'))">
        <ReportAnalyzer>true</ReportAnalyzer>
    </PropertyGroup>
</Project>
