--- # Build and deploy packages
name: 'Build Dotnet'
description: 'Builds and deploys the source'
inputs:
  # General
  PRODUCTION_BUILD:
    description: 'Whether to build a production build'
    required: true

  # NUGET
  NUGET_PACK:
    description: 'Whether to pack packages with feeds'
    required: false
  NUGET_FEED:
    description: 'Nuget feed to push packages to'
    required: false
  NUGET_SYMBOL_FEED:
    description: 'Nuget feed to push packages symbols to'
    required: false
  NUGET_API_KEY:
    description: 'API key to authenticate when pushing packages'
    required: false
  SLEET_CONFIG:
    description: 'Sleet config file'
    required: false
  SLEET_FEED:
    description: 'Sleet feed to push packages to'
    required: false
  DOTNET_DOCKER_PLATFORM:
    description: 'Dotnet docker platform (e.g. linux-arm64)'
    required: false

  # General
  BUILD_VERSION:
    description: 'Build version'
    required: true

  RELEASE_NOTES:
    description: 'Release notes'
    required: false

  BUILD_SQL:
    description: 'Whether to build SQL DB'
    required: true
  DB_FOLDER:
    description: 'Folder where SQL Files live'
    required: false
  REDGATE_EMAIL:
    description: 'Redgate authentication email'
    required: true
  REDGATE_PAT:
    description: 'Redgate authentication Personal Access Token'
    required: true
  SQLCOMPARE_VERSION:
    description: 'Version of SQL Compare to use'
    required: true

  # GENERAL
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  REPO_VISIBILITY:
    description: 'Visibility of the repo'
    required: true

  # DEPLOYMENT
  PROJECT_TO_PUBLISH:
    description: 'Package (root) to deploy'
    required: false

runs:
  using: "composite"
  steps:

    ############################################################################################################
    # DOTNET BUILD
    ############################################################################################################

    - name: "Dotnet: Define Master build settings"
      if: env.Release == 'false'
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: echo "DOTNET_RELEASE_DEFINES=-p:IsProduction=false" >> "$GITHUB_ENV"

    - name: "Dotnet: Define Release build settings"
      if: env.Release == 'false'
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: echo "DOTNET_RELEASE_DEFINES=-p:IsProduction=True" >> "$GITHUB_ENV"

    - name: "Dotnet: Run build check (Pre-Release)"
      if: ${{ (!endsWith(github.repository, 'funfair-build-check')) && (!endsWith(github.repository, '-template')) }}
      uses: ./.github/actions/build-check
      with:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}

    - name: "Dotnet: Restore packages"
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
        dotnet restore --warnaserror -nodeReuse:False -p:NoWarn=MSB4241 -p:SuppressNETCoreSdkPreviewMessage=true || \
        dotnet restore --warnaserror -nodeReuse:False -p:NoWarn=MSB4241 -p:SuppressNETCoreSdkPreviewMessage=true --ignore-failed-sources || \
        dotnet restore --warnaserror -nodeReuse:False -p:NoWarn=MSB4241 -p:SuppressNETCoreSdkPreviewMessage=true --ignore-failed-sources
      env:
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    - name: "Dotnet: Build (Non-Release)"
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: dotnet build --warnaserror --no-restore --configuration Release "-p:Version=${{inputs.BUILD_VERSION}}" "-p:EnableSarif=True" "-p:IsProduction=${{inputs.PRODUCTION_BUILD}}" -nodeReuse:False -p:NoWarn=MSB4241 -p:SuppressNETCoreSdkPreviewMessage=true ${{env.DOTNET_RELEASE_DEFINES}}
      env:
        ReleaseNotes: ${{inputs.RELEASE_NOTES}}
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    ## RUN TESTS
    - name: "Dotnet: Test"
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: dotnet test --warnaserror --no-build --no-restore -noConsoleLogger --configuration Release "-p:Version=${{inputs.BUILD_VERSION}}" "-p:IsProduction=${{inputs.PRODUCTION_BUILD}}" --filter FullyQualifiedName\!~Integration --logger:"trx;LogFilePrefix=testResults" --results-directory ../test-results -nodeReuse:False -p:NoWarn=MSB4241 -p:SuppressNETCoreSdkPreviewMessage=true
      env:
        ReleaseNotes: ${{inputs.RELEASE_NOTES}}
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    # ############################################################################################################
    # # DATABASE BUILD
    # ############################################################################################################
    - name: "SQL: Build"
      if: inputs.BUILD_SQL == 'true'
      uses: ./.github/actions/sql
      with:
        BUILD_VERSION: ${{inputs.BUILD_VERSION}}
        DB_FOLDER: ${{inputs.DB_FOLDER}}
        REDGATE_EMAIL: ${{inputs.REDGATE_EMAIL}}
        REDGATE_PAT: ${{inputs.REDGATE_PAT}}
        SQLCOMPARE_VERSION: ${{inputs.SQLCOMPARE_VERSION}}

    ############################################################################################################
    # Publish ready for deploy
    ############################################################################################################

    - name: "Dotnet: Publish Packages"
      if: inputs.PROJECT_TO_PUBLISH != ''
      uses: ./.github/actions/dotnet-publish
      with:
        PRODUCTION_BUILD: ${{inputs.PRODUCTION_BUILD}}
        BUILD_VERSION: ${{inputs.BUILD_VERSION}}
        RELEASE_NOTES: ${{inputs.RELEASE_NOTES}}
        PLATFORM: ${{inputs.DOTNET_DOCKER_PLATFORM}}
        PROJECT_TO_PUBLISH: ${{inputs.PROJECT_TO_PUBLISH}}

    ############################################################################################################
    # DOTNET PUSH TO NUGET
    ############################################################################################################
    - name: "Dotnet: Pack tool"
      if: inputs.NUGET_PACK == 'true'
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: dotnet pack --warnaserror --configuration Release "-p:Version=${{inputs.BUILD_VERSION}}" "-p:IsProduction=${{inputs.PRODUCTION_BUILD}}" "-p:IncludeSymbols=False" --no-restore -nodeReuse:False -p:NoWarn=MSB4241
      env:
        ReleaseNotes: ${{inputs.RELEASE_NOTES}}
        DOTNET_ROOT: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet/${{github.sha}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
        DOTNET_MULTILEVEL_LOOKUP: "false"
        DOTNET_NOLOGO: "true"
        DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
        DOTNET_JitCollect64BitCounts: "1"
        DOTNET_ReadyToRun: "0"
        DOTNET_TC_QuickJitForLoops: "1"
        DOTNET_TC_CallCountingDelayMs: "0"
        DOTNET_TieredPGO: "1"
        MSBUILDTERMINALLOGGER: "auto"
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    - name: "Dotnet: Copy packed to dist"
      if: inputs.NUGET_PACK == 'true'
      shell: bash
      run: |
        shopt -s globstar
        cp **/*.nupkg "${{github.workspace}}/dist"
      working-directory: ${{github.workspace}}/src

    - name: "Dotnet: Publish Packages to Nuget (With integrated symbol feed)"
      if: |-
        inputs.NUGET_API_KEY != '' &&
        inputs.NUGET_API_KEY != 'SLEET' &&
        inputs.NUGET_PACK == 'true' &&
        (inputs.NUGET_SYMBOL_FEED == '' || inputs.NUGET_SYMBOL_FEED == ' ')
      uses: ./.github/actions/nuget-push-integrated-symbol-feed
      with:
        NUGET_FEED: ${{inputs.NUGET_FEED}}
        NUGET_API_KEY: ${{inputs.NUGET_API_KEY}}

    - name: "Dotnet: Publish Packages to Nuget (With separate symbol feed)"
      if: |-
        inputs.NUGET_API_KEY != '' &&
        inputs.NUGET_API_KEY != 'SLEET' &&
        inputs.NUGET_PACK == 'true' &&
        !(inputs.NUGET_SYMBOL_FEED == '' || inputs.NUGET_SYMBOL_FEED == ' ')
      uses: ./.github/actions/nuget-push-separate-symbol-feed
      with:
        NUGET_FEED: ${{inputs.NUGET_FEED}}
        NUGET_SYMBOL_FEED: ${{inputs.NUGET_SYMBOL_FEED}}
        NUGET_API_KEY: ${{inputs.NUGET_API_KEY}}

    - name: "Dotnet: Publish Packages using sleet"
      if: |-
        inputs.NUGET_API_KEY == 'SLEET' &&
        inputs.NUGET_PACK == 'true' &&
        !(inputs.NUGET_SYMBOL_FEED == '' || inputs.NUGET_SYMBOL_FEED == ' ')
      uses: ./.github/actions/sleet
      with:
        SLEET_CONFIG: ${{ inputs.SLEET_CONFIG }}
        SLEET_FEED: ${{inputs.SLEET_FEED}}
