name: Find branches without PR's

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/create-prs-for-stale-branches.yml"
  schedule:
  - cron: "0 1 * * *"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - run: |
          echo "Repo: ${{ github.repository }}"
          echo "Owner: ${{ github.repository_owner }}"
      - run: sudo apt install -y jq
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: main
          repository: ${{ github.repository }}
#          token: ${{ secrets.SOURCE_PUSH_TOKEN }}

      - id: set-matrix
        run: echo "branches=$(git branch --remote --format='%(refname:short)' | grep -Po 'origin/\K[^*]*' | grep -vE 'HEAD|release/|hotfix/' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      branches: ${{ steps.set-matrix.outputs.branches }}

  check-branch:
    needs: build-matrix
    runs-on: ubuntu-latest
    # runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        branch: ${{ fromJson(needs.build-matrix.outputs.branches) }}
    steps:
      - run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: main
          repository: ${{ github.repository }}
#          token: ${{ secrets.SOURCE_PUSH_TOKEN }}

      - id: detection
        run: |
          echo "defaultbranch=$(git remote show origin | grep -Po 'HEAD\sbranch:\s+\K[^.*]*')" >> $GITHUB_OUTPUT

      # On Default branch
      - if: ${{ steps.detection.outputs.defaultbranch == matrix.branch }}
        run: echo "On Default branch - don't do anything"


      # On Non-Default branch
      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch }}
        run: echo "On non-default branch"

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch }}
        uses: juliangruber/find-pull-request-action@v1.7.2
        id: find-pull-request
        with:
          branch: "${{ matrix.branch }}"
#          github-token: ${{ secrets.SOURCE_PUSH_TOKEN }}
      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch }}
        run: echo "Pull Request ${{ steps.find-pull-request.outputs.number }} ( ${{ steps.find-pull-request.outputs.head-sha }})"
      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' }}
        id: aheadbehind
        name: Check Ahead\Behind Status
        run: |
          echo "Check to see if ${{steps.detection.outputs.defaultbranch}} is ahead or behind ${{matrix.branch}}..."
          git rev-list --left-right --count origin/${{steps.detection.outputs.defaultbranch}}...origin/${{matrix.branch}}
          git rev-list --left-right --count origin/${{steps.detection.outputs.defaultbranch}}...origin/${{matrix.branch}} | awk '{ print "${{matrix.branch}} is behind ${{steps.detection.outputs.defaultbranch}} by "$1" commit(s)" }'
          git rev-list --left-right --count origin/${{steps.detection.outputs.defaultbranch}}...origin/${{matrix.branch}} | awk '{ print "behind="$1 }' >> $GITHUB_OUTPUT
          git rev-list --left-right --count origin/${{steps.detection.outputs.defaultbranch}}...origin/${{matrix.branch}} | awk '{ print "${{matrix.branch}} is ahead of ${{steps.detection.outputs.defaultbranch}} by "$2" commit(s)" }'
          git rev-list --left-right --count origin/${{steps.detection.outputs.defaultbranch}}...origin/${{matrix.branch}} | awk '{ print "ahead="$2 }' >> $GITHUB_OUTPUT
          echo "dayssinceupdate=$((($(date +%s)-$(date +%s --date @$(git log -1 --format=%ct origin/${{matrix.branch}})))/(3600*24)))" >> $GITHUB_OUTPUT
          echo "COMMIT_MSG=$(git log -1 --pretty=%B origin/${{matrix.branch}})" >> $GITHUB_OUTPUT

      # Non-default - ahead of default branch, and no -re-existing PR then create one.
      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' && steps.aheadbehind.outputs.ahead != 0 && steps.aheadbehind.outputs.dayssinceupdate > 7 }}
        id: pr-template
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: ./.github/PULL_REQUEST_TEMPLATE.md

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' && steps.aheadbehind.outputs.ahead != 0 && steps.aheadbehind.outputs.dayssinceupdate > 7 }}
        name: Get last commit message
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B origin/${{matrix.branch}})" >> $GITHUB_ENV

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' && steps.aheadbehind.outputs.ahead != 0 && steps.aheadbehind.outputs.dayssinceupdate > 7 }}
        id: open-pr
        uses: repo-sync/pull-request@v2.8
        with:
          source_branch: ${{matrix.branch}}       # If blank, default: triggered branch
          destination_branch: ${{steps.detection.outputs.defaultbranch}}            # If blank, default: master
          pr_assignee: "${{ github.actor }}"    # Comma-separated list (no spaces)
          pr_label: "auto-pr,stale"             # Comma-separated list (no spaces)
          pr_draft: true                        # Creates pull request as draft
          pr_title: "${{ steps.aheadbehind.outputs.COMMIT_MSG }} [No commits for ${{steps.aheadbehind.outputs.dayssinceupdate}} days]"
          pr_body: "${{ steps.pr-template.outputs.content }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' && steps.aheadbehind.outputs.ahead != 0 && steps.aheadbehind.outputs.dayssinceupdate > 7 }}
        name: New PR Details
        run: |
            echo "URL: ${{steps.open-pr.outputs.pr_url}}"
            echo "PR: ${{steps.open-pr.outputs.pr_number}}"
            echo "CF: ${{steps.open-pr.outputs.has_changed_files}}"

      # TODO: Switch to actions/labeler@Vx.y if https://github.com/actions/labeler/pull/349 is merged and a release created
      - if: ${{ steps.open-pr.outputs.pr_number != '' }}
        uses: credfeto/labeler@feature/pass-in-pull-request-or-issue
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
          pr-number: ${{steps.open-pr.outputs.pr_number}}

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' && steps.aheadbehind.outputs.behind != 0 && steps.aheadbehind.outputs.ahead != 0 && steps.aheadbehind.outputs.dayssinceupdate > 7 }}
        name: Rebase
        run: echo "Rebase?"

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' && steps.aheadbehind.outputs.ahead == '0' && steps.aheadbehind.outputs.dayssinceupdate > 60 }}
        name: Delete Branch
        uses: dawidd6/action-delete-branch@v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ matrix.branch }}

      - if: ${{ steps.detection.outputs.defaultbranch != matrix.branch && steps.find-pull-request.outputs.number == '' }}
        run: |
          echo "Ahead: ${{ steps.aheadbehind.outputs.ahead }}"
          echo "Behind: ${{ steps.aheadbehind.outputs.behind }}"
          echo "Last Commit: ${{ steps.aheadbehind.outputs.dayssinceupdate }} days ago"

